<a href="https://colab.research.google.com/github/dziubek3/NaiveBayes_ComputerVision/blob/master/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
# Michal Kowalczyk ZID: 1843873
#The beginning of Naive Bayes Program With Computer Vision (490 - Assignment 1)

import numpy as np
import math
from urllib.request import *
arr = []
with urlopen("https://raw.githubusercontent.com/dziubek3/NaiveBayes_ComputerVision/master/trainingimages") as response:
  for line in response:
    line = line.decode('utf-8').rstrip("\n\r")
    arr.append(list(line))
    
arr = np.array(arr)
arr = np.reshape(arr,(5000,28,28))
arr[arr==' ']=0
arr[arr=='+']=1
arr[arr=='#']=1

############################################################################################################################

digitList = []
digitOccurence = [0,0,0,0,0,0,0,0,0,0] #this holds how many times 0 - 9 occurs.

with urlopen("https://raw.githubusercontent.com/dziubek3/NaiveBayes_ComputerVision/master/traininglabels") as trainLabels:
   for line2 in trainLabels:
    line2 = line2.decode('utf-8').rstrip("\n\r\s")
    digitList.append(list(line2))

digitList = np.array(digitList)
digitList = np.reshape(digitList,(5000))
    

#wanted to do this as a case switch statement first, but I don't understand it in python too well. Iterate through the digitList with x being the iteration and pass x into the case/switch statement, and for each number, increase the respective digit in digitOccurence.
for x in digitList:
  if x == "0":
     digitOccurence[0] = digitOccurence[0] + 1
  if x== "1":
     digitOccurence[1] = digitOccurence[1] + 1
  if x=="2":
     digitOccurence[2] = digitOccurence[2] + 1
  if x=="3":
     digitOccurence[3] = digitOccurence[3] + 1
  if x=="4":
     digitOccurence[4] = digitOccurence[4] + 1
  if x=="5":
     digitOccurence[5] = digitOccurence[5] + 1
  if x=="6":
     digitOccurence[6] = digitOccurence[6] + 1
  if x=="7":
     digitOccurence[7] = digitOccurence[7] + 1
  if x=="8":
     digitOccurence[8] = digitOccurence[8] + 1
  if x=="9":
     digitOccurence[9] = digitOccurence[9] + 1
    
      
##########################################################################################################################      
#this allows for each pixel in our 28 x 28 pixel image keep the counter for how many 0's and 1's there are in each i x j image for each class IE: D0, D1 ... etc
D0, D1, D2, D3, D4, D5, D6, D7, D8, D9 = (np.zeros((28,28,2),dtype=np.float) for i in range(10))
########################################################################################################################## 
##MIGHT HAVE TO HARDCODE THE CASE FOR EACH digit. IE: 0-9 if else statements in our while loop below.
def digitSelector(number):
  switcher = {
      0: D0,
      1: D1,
      2: D2,
      3: D3,
      4: D4,
      5: D5,
      6: D6,
      7: D7,
      8: D8,
      9: D9
  }
  return switcher.get(number)
#####################################

listCounter = 0
while listCounter < 5000:
  for x in digitList:
    if x == "0":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D0[i,j,0] += 1
          else:
            D0[i,j,1] += 1
    if x == "1":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D1[i,j,0] += 1
          else:
            D1[i,j,1] += 1
    if x == "2":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D2[i,j,0] += 1
          else:
            D2[i,j,1] += 1
    if x == "3":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D3[i,j,0] += 1
          else:
            D3[i,j,1] += 1
    if x == "4":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D4[i,j,0] += 1
          else:
            D4[i,j,1] += 1
    if x == "5":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D5[i,j,0] += 1
          else:
            D5[i,j,1] += 1
    if x == "6":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D6[i,j,0] += 1
          else:
            D6[i,j,1] += 1
    if x == "7":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D7[i,j,0] += 1
          else:
            D7[i,j,1] += 1
    if x == "8":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D8[i,j,0] += 1
          else:
            D8[i,j,1] += 1
    if x == "9":
      for i in range(28):
        for j in range(28):
          if arr[listCounter,i,j] == "0":
            D9[i,j,0] += 1
          else:
            D9[i,j,1] += 1    
    listCounter = listCounter + 1

#Laplacian Smoothing, K. 
#These equations find our likelihoods for each pixel, given that the pixel is either a 0 or a 1. 
k = 1    
for i in range(28):
  for j in range(28):
    D0[i,j,0] = (D0[i,j,0] + k)/(digitOccurence[0]+ 2*k)
    D0[i,j,1] = (D0[i,j,1] + k)/(digitOccurence[0]+ 2*k)
    D1[i,j,0] = (D1[i,j,0] + k)/(digitOccurence[1]+ 2*k)
    D1[i,j,1] = (D1[i,j,1] + k)/(digitOccurence[1]+ 2*k)
    D2[i,j,0] = (D2[i,j,0] + k)/(digitOccurence[2]+ 2*k)
    D2[i,j,1] = (D2[i,j,1] + k)/(digitOccurence[2]+ 2*k) 
    D3[i,j,0] = (D3[i,j,0] + k)/(digitOccurence[3]+ 2*k)
    D3[i,j,1] = (D3[i,j,1] + k)/(digitOccurence[3]+ 2*k)
    D4[i,j,0] = (D4[i,j,0] + k)/(digitOccurence[4]+ 2*k)
    D4[i,j,1] = (D4[i,j,1] + k)/(digitOccurence[4]+ 2*k)
    D5[i,j,0] = (D5[i,j,0] + k)/(digitOccurence[5]+ 2*k)
    D5[i,j,1] = (D5[i,j,1] + k)/(digitOccurence[5]+ 2*k)
    D6[i,j,0] = (D6[i,j,0] + k)/(digitOccurence[6]+ 2*k)
    D6[i,j,1] = (D6[i,j,1] + k)/(digitOccurence[6]+ 2*k)
    D7[i,j,0] = (D7[i,j,0] + k)/(digitOccurence[7]+ 2*k)
    D7[i,j,1] = (D7[i,j,1] + k)/(digitOccurence[7]+ 2*k)
    D8[i,j,0] = (D8[i,j,0] + k)/(digitOccurence[8]+ 2*k)
    D8[i,j,1] = (D8[i,j,1] + k)/(digitOccurence[8]+ 2*k)
    D9[i,j,0] = (D9[i,j,0] + k)/(digitOccurence[9]+ 2*k)
    D9[i,j,1] = (D9[i,j,1] + k)/(digitOccurence[9]+ 2*k)


#Prior equation, self explanatory    
PriorD0 = digitOccurence[0]/5000
PriorD1 = digitOccurence[1]/5000
PriorD2 = digitOccurence[2]/5000
PriorD3 = digitOccurence[3]/5000
PriorD4 = digitOccurence[4]/5000
PriorD5 = digitOccurence[5]/5000
PriorD6 = digitOccurence[6]/5000
PriorD7 = digitOccurence[7]/5000
PriorD8 = digitOccurence[8]/5000
PriorD9 = digitOccurence[9]/5000



######################################################################################################
#This transforms our testing data into readable data for the purpose of this assignment.

testingImages = []
with urlopen("https://raw.githubusercontent.com/dziubek3/NaiveBayes_ComputerVision/master/testimages") as response:
  for line in response:
    line = line.decode('utf-8').rstrip("\n\r")
    testingImages.append(list(line))
    
testingImages = np.array(testingImages)
testingImages = np.reshape(testingImages,(1000,28,28))
testingImages[testingImages==' ']=0
testingImages[testingImages=='+']=1
testingImages[testingImages=='#']=1

#this will hold our labels that our algorithm decides using our NaiveBayes alogorithm
ourResults = np.zeros((1000),dtype=np.int)
 
for x in range(1000):  #counter for which images
  Posterior0 = math.log(PriorD0) #the starting value for each posterior probability 
  Posterior1 = math.log(PriorD1)
  Posterior2 = math.log(PriorD2)
  Posterior3 = math.log(PriorD3)
  Posterior4 = math.log(PriorD4) 
  Posterior5 = math.log(PriorD5)
  Posterior6 = math.log(PriorD6)
  Posterior7 = math.log(PriorD7)
  Posterior8 = math.log(PriorD8)
  Posterior9 = math.log(PriorD9)
  for y in range(28): #row counter
    for z in range(28): #column counter
      pixelValue = int(testingImages[x,y,z])  
      Posterior0 = Posterior0 + math.log(D0[y,z,pixelValue])
      Posterior1 = Posterior1 + math.log(D1[y,z,pixelValue])
      Posterior2 = Posterior2 + math.log(D2[y,z,pixelValue])
      Posterior3 = Posterior3 + math.log(D3[y,z,pixelValue])
      Posterior4 = Posterior4 + math.log(D4[y,z,pixelValue])
      Posterior5 = Posterior5 + math.log(D5[y,z,pixelValue])
      Posterior6 = Posterior6 + math.log(D6[y,z,pixelValue])
      Posterior7 = Posterior7 + math.log(D7[y,z,pixelValue])
      Posterior8 = Posterior8 + math.log(D8[y,z,pixelValue])
      Posterior9 = Posterior9 + math.log(D9[y,z,pixelValue])
  maxPosterior = max(Posterior0, Posterior1, Posterior2, Posterior3, Posterior4, Posterior5, Posterior6, Posterior7, Posterior8, Posterior9) #find the max posterior
  if maxPosterior == Posterior0:
    ourResults[x] = 0
  elif maxPosterior == Posterior1:
    ourResults[x] = 1
  elif maxPosterior == Posterior2:
    ourResults[x] = 2  
  elif maxPosterior == Posterior3:
    ourResults[x] = 3  
  elif maxPosterior == Posterior4:
    ourResults[x] = 4  
  elif maxPosterior == Posterior5:
    ourResults[x] = 5
  elif maxPosterior == Posterior6:
    ourResults[x] = 6
  elif maxPosterior == Posterior7:
    ourResults[x] = 7
  elif maxPosterior == Posterior8:
    ourResults[x] = 8
  elif maxPosterior == Posterior9:
    ourResults[x] = 9

###### This is to count how many times each digit occured from our RESULTS 
resultsDOccurence = [0,0,0,0,0,0,0,0,0,0]
for x in ourResults:
  if x == 0:
     resultsDOccurence[0] = resultsDOccurence[0] + 1
  if x== 1:
     resultsDOccurence[1] = resultsDOccurence[1] + 1
  if x== 2:
     resultsDOccurence[2] = resultsDOccurence[2] + 1
  if x== 3:
     resultsDOccurence[3] = resultsDOccurence[3] + 1
  if x== 4:
     resultsDOccurence[4] = resultsDOccurence[4] + 1
  if x== 5:
     resultsDOccurence[5] = resultsDOccurence[5] + 1
  if x== 6:
     resultsDOccurence[6] = resultsDOccurence[6] + 1
  if x== 7:
     resultsDOccurence[7] = resultsDOccurence[7] + 1
  if x== 8:
     resultsDOccurence[8] = resultsDOccurence[8] + 1
  if x== 9:
     resultsDOccurence[9] = resultsDOccurence[9] + 1
      
###############################
testingDigitList = []
correctDOccurence = [0,0,0,0,0,0,0,0,0,0] #this holds how many times 0 - 9 occurs, the ACTUAL amount (the correct amount)

with urlopen("https://raw.githubusercontent.com/dziubek3/NaiveBayes_ComputerVision/master/testlabels") as testLabels:
   for line in testLabels:
    line = line.decode('utf-8').rstrip("\n\r\s")
    testingDigitList.append(list(line))

testingDigitList = np.array(testingDigitList)
testingDigitList = np.reshape(testingDigitList,(1000))

for x in testingDigitList:
  if x == "0":
     correctDOccurence[0] = correctDOccurence[0] + 1
  if x== "1":
     correctDOccurence[1] = correctDOccurence[1] + 1
  if x=="2":
     correctDOccurence[2] = correctDOccurence[2] + 1
  if x=="3":
     correctDOccurence[3] = correctDOccurence[3] + 1
  if x=="4":
     correctDOccurence[4] = correctDOccurence[4] + 1
  if x=="5":
     correctDOccurence[5] = correctDOccurence[5] + 1
  if x=="6":
     correctDOccurence[6] = correctDOccurence[6] + 1
  if x=="7":
     correctDOccurence[7] = correctDOccurence[7] + 1
  if x=="8":
     correctDOccurence[8] = correctDOccurence[8] + 1
  if x=="9":
     correctDOccurence[9] = correctDOccurence[9] + 1

#Our 10x10 Confusion Matrix, I have this part set up like so.. 
resultsMatrix = np.zeros((10,10),dtype=np.float)
for x in range(1000): #since there are 1000 testing entries.
  if int(testingDigitList[x]) == ourResults[x]: # if the x-th digit in the testingList is the same as our Results
    resultsMatrix[ourResults[x],ourResults[x]] = resultsMatrix[ourResults[x],ourResults[x]] + 1 #then add one to the Confusion Matrix in the digit,digit spot. (I.E. Our results = 7, the actual number is 7, +1 in the 7,7 spot in the matrix.)
  else:
    resultsMatrix[int(testingDigitList[x]), ourResults[x]] = resultsMatrix[int(testingDigitList[x]),ourResults[x]] + 1 #otherwise, add one to the spot at testingDigit,ourResultDigit
for i in range(10):
  for j in range(10):
    resultsMatrix[i,j] = resultsMatrix[i,j] / correctDOccurence[i] #we want this as a percentage, so we divide each number by the correct amount of each digit there's supposed to be 
   
np.set_printoptions(precision=2)
print(resultsMatrix)
  

 

[[0.84 0.   0.01 0.   0.01 0.06 0.03 0.   0.04 0.  ]
 [0.   0.96 0.01 0.   0.   0.02 0.01 0.   0.   0.  ]
 [0.01 0.03 0.78 0.04 0.01 0.   0.06 0.01 0.05 0.02]
 [0.   0.02 0.   0.79 0.   0.03 0.02 0.06 0.02 0.06]
 [0.   0.01 0.   0.   0.77 0.   0.03 0.01 0.02 0.17]
 [0.02 0.02 0.01 0.13 0.03 0.67 0.01 0.01 0.02 0.07]
 [0.01 0.07 0.04 0.   0.04 0.05 0.76 0.   0.02 0.  ]
 [0.   0.06 0.03 0.   0.03 0.   0.   0.73 0.03 0.13]
 [0.02 0.01 0.03 0.14 0.02 0.06 0.   0.01 0.6  0.12]
 [0.01 0.01 0.01 0.03 0.09 0.02 0.   0.02 0.01 0.8 ]]


In [0]:
#ToolBox for Debugging.
print(ourResults)